server:
    # Should the server send a prefix before every message? (true/false)
    use-prefix: true
    
    web:
        # What port should the web-server use?
        port: 8080
        # The path (starting from the UltraAuthenticator folder) to the HTML files.
        path: "/web"
        # Should the web server send a notification to the console when someone connects? (true/false)
        verbose: false
        
    authentication:
        # How many attempts should a player have to enter the correct code before they are kicked?
        number-of-attempts: 3